const games = [
  { id: 0, name: "Minecraft", file: "/games/minecraft.html", icon: "https://cdn2.steamgriddb.com/icon/bf6423635e56a99e9df17852c6bfadca/32/512x512.png", banner: "https://mmos.com/wp-content/uploads/2015/11/minecraft-banner.jpg", desc: "Minecraft Unblocked lets you dive into the ultimate sandbox adventure, free from restrictions. Whether you're crafting towering castles or surviving the night against mobs, this version of Minecraft is perfect for playing at school or work—no downloads, no logins, just pure creativity. Build, mine, and explore endless worlds right in your browser. If you're looking for a fun and free way to enjoy the game, Minecraft Unblocked is the best way to play online. Start building today—anytime, anywhere!"},
  { id: 1, "name":"Cookie Clicker","file":"/games/cookieclicker.html","icon":"https://play-lh.googleusercontent.com/Z1MOuuiD05ZN5LkVmMEvKF0mqAc-FknaQ2j8s4dZiO-LSPQX4EEA3RVJdlQEtxe96ok","banner":"https://cdn2.steamgriddb.com/hero_thumb/6b7d0fc39acc509d5910db3d0af96052.jpg","desc":"Cookie Clicker Unblocked is the addictive idle game where you bake as many cookies as possible by simply clicking. Start with one giant cookie, click to earn your first treats, then unlock upgrades, factories, and grandmas to keep the cookies flowing even while you’re not clicking.\n\n🎮 How to Play\n\nClick the cookie to generate your first batch.\n\nBuy upgrades to boost your production rate.\n\nAutomate with grandmas, farms, and factories.\n\nKeep growing until your cookie empire takes over the galaxy!\n\n⭐ Features\n\nSimple but endlessly addictive gameplay.\n\nUnlock achievements and rare upgrades.\n\nPlay instantly in your browser, no downloads needed.\n\n100% free and school-safe.\n\n🚀 Why Play Cookie Clicker Unblocked?\n\nCookie Clicker is perfect when you want a fun, stress-free game you can leave running in the background. Since this version is unblocked, you can play at school, work, or anywhere without restrictions. Grow your cookie empire and see how many cookies you can bake!\n\n👉 Play Cookie Clicker Unblocked now and start your sweet adventure."},
  { id: 2, "name":"1v1.LOL","file":"/games/1v1lol.html","icon":"https://img.utdstc.com/icon/983/22a/98322a3b2be892eed31589906ffd949b68bcccc9a21ba562987965b5ec6bc6de:200","banner":"https://cdn.akamai.steamstatic.com/steam/apps/2305790/extras/1v1_game_banner.png?t=1694685389","desc":"<h1>🎯 1v1.LOL Unblocked – Play Online Free</h1>\n\n<p><strong>1v1.LOL Unblocked</strong> is an exciting online multiplayer shooting and building game where you face off against opponents in fast-paced 1v1 battles. Build structures, strategize your attacks, and outsmart your enemies to become the ultimate champion.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Join a 1v1 match and immediately start building to protect yourself.</li>\n  <li>Collect weapons and resources to gain an advantage.</li>\n  <li>Use walls, ramps, and platforms to outmaneuver your opponent.</li>\n  <li>Eliminate your rival to win the round and climb the leaderboard.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Fast-paced, skill-based 1v1 battles.</li>\n  <li>Intuitive building mechanics and creative strategies.</li>\n  <li>Play instantly in your browser, no downloads required.</li>\n  <li>100% free and school-safe for unblocked play.</li>\n</ul>\n\n<h2>🚀 Why Play 1v1.LOL Unblocked?</h2>\n<p>1v1.LOL is perfect for players who love competitive, action-packed games that test both reflexes and strategy. With this <strong>unblocked version</strong>, you can jump into battles at school, work, or anywhere without restrictions. Improve your skills, dominate your opponents, and become a 1v1 champion!</p>\n\n<p><strong>👉 Play 1v1.LOL Unblocked now and show off your building and shooting skills!</strong></p>"},
  { id: 3, "name":"Geometry Dash","file":"/games/geometrydash.html","icon":"https://cdn2.steamgriddb.com/icon_thumb/31073475fc4fe0f27c6b876472f0888e.png","banner":"https://i.ytimg.com/vi/5qEYn_WW_RQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDWerVCcQi41HwZgeu0lpZU6yRXVA","desc":"<h1>🚀 Geometry Dash Unblocked – Play Online Free</h1>\n\n<p><strong>Geometry Dash Unblocked</strong> is a fast-paced rhythm-based platformer where you jump, fly, and flip through challenging levels filled with obstacles. Test your reflexes and timing as you navigate through colorful, music-driven worlds.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use precise timing to jump over spikes and avoid hazards.</li>\n  <li>Follow the rhythm of the music to anticipate obstacles.</li>\n  <li>Unlock new levels as you progress through increasingly challenging stages.</li>\n  <li>Practice, memorize patterns, and beat your high scores!</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Fast-paced, challenging gameplay for all skill levels.</li>\n  <li>Multiple levels with unique music and obstacles.</li>\n  <li>Play instantly in your browser, no downloads required.</li>\n  <li>100% free and school-safe for unblocked play.</li>\n</ul>\n\n<h2>🚀 Why Play Geometry Dash Unblocked?</h2>\n<p>Geometry Dash is perfect for players who love rhythm-based platformers and challenging gameplay. This <strong>unblocked version</strong> lets you play at school, work, or anywhere without restrictions. Improve your reflexes, conquer difficult levels, and aim for the top of the leaderboard!</p>\n\n<p><strong>👉 Play Geometry Dash Unblocked now and test your timing and skills!</strong></p>\n"},
];

for(let gamei in games) {
    let game = games[gamei];
    document.getElementById("games-sidebar").innerHTML += `<a href='${window.location.origin}${game.file}'><img src='${game.icon}'>${game.name}</a>`
}

if(document.getElementById("new")) {
  for(let i = games.length-1; i > games.length - 10; i--) {
    if(games[i]) {
      document.getElementById("new").innerHTML += `<div onclick="window.location.href = '${window.location.origin}${games[i].file}'" class="game-card"><img src="${games[i].banner}"><h1>${games[i].name}</h1><div class="desc">${games[i].desc}</div></div>`;
    }
  }
}

if(document.getElementById("all")) {
  for(let i = 0; i < games.length; i++) {
    if(games[i]) {
      document.getElementById("all").innerHTML += `<div onclick="window.location.href = '${window.location.origin}${games[i].file}'" class="game-icon"><img src="${games[i].icon}"><h1 class="glass">${games[i].name}</h1></div>`;
    }
  }
}

