const games = [
  { id: 0, name: "Minecraft", file: "/games/minecraft.html", icon: "https://cdn2.steamgriddb.com/icon/bf6423635e56a99e9df17852c6bfadca/32/512x512.png", banner: "https://mmos.com/wp-content/uploads/2015/11/minecraft-banner.jpg", desc: "Minecraft Unblocked lets you dive into the ultimate sandbox adventure, free from restrictions. Whether you're crafting towering castles or surviving the night against mobs, this version of Minecraft is perfect for playing at school or work—no downloads, no logins, just pure creativity. Build, mine, and explore endless worlds right in your browser. If you're looking for a fun and free way to enjoy the game, Minecraft Unblocked is the best way to play online. Start building today—anytime, anywhere!"},
  { id: 1, "name":"Cookie Clicker","file":"/games/cookieclicker.html","icon":"https://play-lh.googleusercontent.com/Z1MOuuiD05ZN5LkVmMEvKF0mqAc-FknaQ2j8s4dZiO-LSPQX4EEA3RVJdlQEtxe96ok","banner":"https://cdn2.steamgriddb.com/hero_thumb/6b7d0fc39acc509d5910db3d0af96052.jpg","desc":"Cookie Clicker Unblocked is the addictive idle game where you bake as many cookies as possible by simply clicking. Start with one giant cookie, click to earn your first treats, then unlock upgrades, factories, and grandmas to keep the cookies flowing even while you’re not clicking.\n\n🎮 How to Play\n\nClick the cookie to generate your first batch.\n\nBuy upgrades to boost your production rate.\n\nAutomate with grandmas, farms, and factories.\n\nKeep growing until your cookie empire takes over the galaxy!\n\n⭐ Features\n\nSimple but endlessly addictive gameplay.\n\nUnlock achievements and rare upgrades.\n\nPlay instantly in your browser, no downloads needed.\n\n100% free and school-safe.\n\n🚀 Why Play Cookie Clicker Unblocked?\n\nCookie Clicker is perfect when you want a fun, stress-free game you can leave running in the background. Since this version is unblocked, you can play at school, work, or anywhere without restrictions. Grow your cookie empire and see how many cookies you can bake!\n\n👉 Play Cookie Clicker Unblocked now and start your sweet adventure."},
  { id: 2, "name":"Geometry Dash","file":"/games/geometrydash.html","icon":"https://cdn2.steamgriddb.com/icon_thumb/31073475fc4fe0f27c6b876472f0888e.png","banner":"https://i.ytimg.com/vi/5qEYn_WW_RQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDWerVCcQi41HwZgeu0lpZU6yRXVA","desc":"<h1>🚀 Geometry Dash Unblocked – Play Online Free</h1>\n\n<p><strong>Geometry Dash Unblocked</strong> is a fast-paced rhythm-based platformer where you jump, fly, and flip through challenging levels filled with obstacles. Test your reflexes and timing as you navigate through colorful, music-driven worlds.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use precise timing to jump over spikes and avoid hazards.</li>\n  <li>Follow the rhythm of the music to anticipate obstacles.</li>\n  <li>Unlock new levels as you progress through increasingly challenging stages.</li>\n  <li>Practice, memorize patterns, and beat your high scores!</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Fast-paced, challenging gameplay for all skill levels.</li>\n  <li>Multiple levels with unique music and obstacles.</li>\n  <li>Play instantly in your browser, no downloads required.</li>\n  <li>100% free and school-safe for unblocked play.</li>\n</ul>\n\n<h2>🚀 Why Play Geometry Dash Unblocked?</h2>\n<p>Geometry Dash is perfect for players who love rhythm-based platformers and challenging gameplay. This <strong>unblocked version</strong> lets you play at school, work, or anywhere without restrictions. Improve your reflexes, conquer difficult levels, and aim for the top of the leaderboard!</p>\n\n<p><strong>👉 Play Geometry Dash Unblocked now and test your timing and skills!</strong></p>\n"},
  { id: 3, "name":"Slope","file":"/games/slope.html","icon":"https://play-lh.googleusercontent.com/uJn2i9h7KxYQarC_c3K4qH6o7gLtflFnhD_dN14MNkzHJ1NeNFzCL69jpB5mT0vCoQs","banner":"https://slope-games.io/data/image/options/slope-game-banner.jpg","desc":"<h1>🌀 Slope Unblocked – Play Online Free</h1>\n\n<p><strong>Slope Unblocked</strong> is a fast-paced endless runner game where you control a glowing ball rolling down a never-ending 3D slope. Dodge obstacles, stay on track, and test your reflexes as the speed increases with every second.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys to steer your ball left and right.</li>\n  <li>Avoid red walls and deadly obstacles that end your run instantly.</li>\n  <li>Stay balanced on narrow platforms as the slope gets faster.</li>\n  <li>Challenge yourself to beat your high score with every run.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Simple controls with intense, addictive gameplay.</li>\n  <li>Dynamic 3D graphics and increasing difficulty.</li>\n  <li>Endless replayability with high-score challenges.</li>\n  <li>100% free, browser-based, and school-safe unblocked play.</li>\n</ul>\n\n<h2>🚀 Why Play Slope Unblocked?</h2>\n<p>Slope is the ultimate reflex and reaction test, perfect for quick gaming sessions or long high-score grinds. With this <strong>unblocked version</strong>, you can enjoy the game at school, work, or anywhere without restrictions. Stay focused, control your ball, and see how far you can go down the slope!</p>\n\n<p><strong>👉 Play Slope Unblocked now and put your reflexes to the ultimate test!</strong></p>\n"},
  { id: 4, "name":"Super Mario 64","file":"/games/supermario 64.html","icon":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/06373d2c-2485-4865-ab62-77409cc10433/debmz1m-e82625f7-8b3a-449b-9836-892c6da1106d.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA2MzczZDJjLTI0ODUtNDg2NS1hYjYyLTc3NDA5Y2MxMDQzM1wvZGVibXoxbS1lODI2MjVmNy04YjNhLTQ0OWItOTgzNi04OTJjNmRhMTEwNmQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.LOgCzyTQiDvIMMBq3OUnuDMXmwv-vMwlAmNRgZe55pg","banner":"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3abd9d7a-a56a-403c-aca5-22b4e5cf203f/diamq71-53691cb9-14f6-41a1-96ba-209ff13feef9.jpg/v1/fill/w_1280,h_720,q_75,strp/super_mario_64_banner__by_zackfire456_diamq71-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvM2FiZDlkN2EtYTU2YS00MDNjLWFjYTUtMjJiNGU1Y2YyMDNmXC9kaWFtcTcxLTUzNjkxY2I5LTE0ZjYtNDFhMS05NmJhLTIwOWZmMTNmZWVmOS5qcGciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.uCVmA6ghojFVN1RVJWldpb9YWVZAZLXyzLQdekaYAW0","desc":"<h1>🍄 Super Mario 64 Unblocked – Play Online Free</h1>\n\n<p><strong>Super Mario 64 Unblocked</strong> is the legendary 3D platformer that brings Mario’s world to life like never before. Jump, run, and explore vast levels filled with secrets, stars, and enemies as you help Mario save Princess Peach from Bowser’s castle.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys or WASD to move Mario through 3D environments.</li>\n  <li>Jump, triple-jump, and wall-kick your way across obstacles.</li>\n  <li>Collect stars hidden throughout each level to unlock new areas.</li>\n  <li>Defeat Bowser’s minions and face Bowser himself in epic battles.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Classic 3D platforming with iconic Mario gameplay.</li>\n  <li>Large open-world levels packed with secrets and challenges.</li>\n  <li>Play instantly in your browser – no downloads required.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Super Mario 64 Unblocked?</h2>\n<p>Super Mario 64 is one of the most beloved games of all time, known for its groundbreaking 3D design and timeless fun. With this <strong>unblocked version</strong>, you can relive Mario’s classic adventure anywhere – at school, work, or home – without restrictions. Explore, collect stars, and take on Bowser in this nostalgic masterpiece.</p>\n\n<p><strong>👉 Play Super Mario 64 Unblocked now and experience the classic 3D adventure!</strong></p>\n"},
  { id: 5, "name":"Chess","file":"/games/chess.html","icon":"https://img.icons8.com/?size=512&id=C5LTcmsc3cr0&format=png","banner":"https://static.vecteezy.com/system/resources/thumbnails/005/389/700/small_2x/a-chess-set-in-black-on-a-white-isolated-background-world-chess-day-banner-for-the-holiday-in-the-chess-style-illustration-vector.jpg","desc":"<h1>♟️ Chess Unblocked – Play Online Free</h1>\n\n<p><strong>Chess Unblocked</strong> is the classic strategy board game brought to your browser, where you can test your mind against the computer or a friend. Outsmart your opponent, control the board, and checkmate the king to win.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Move your pieces strategically across the board.</li>\n  <li>Control the center to gain an advantage.</li>\n  <li>Use tactics like forks, pins, and skewers to outmaneuver your opponent.</li>\n  <li>Checkmate the opposing king to secure victory.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Classic chess gameplay in an easy-to-use online format.</li>\n  <li>Play against AI or a friend in multiplayer mode.</li>\n  <li>No downloads or sign-ups required – play instantly in your browser.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Chess Unblocked?</h2>\n<p>Chess is one of the oldest and most respected games of strategy, perfect for sharpening your mind and testing your problem-solving skills. With this <strong>unblocked version</strong>, you can enjoy the game anytime – at school, work, or home – without restrictions. Challenge yourself, improve your skills, and climb to grandmaster-level play.</p>\n\n<p><strong>👉 Play Chess Unblocked now and become the ultimate strategist!</strong></p>\n"},
  { id: 6, "name":"2048","file":"/games/2048.html","icon":"https://upload.wikimedia.org/wikipedia/commons/1/1a/2048_Icon.png","banner":"https://cdn.html5gameportal.com/images/b5efa098-7ea0-4825-86fc-33293b742888-2048_banner.png","desc":"<h1>🔢 2048 Unblocked – Play Online Free</h1>\n\n<p><strong>2048 Unblocked</strong> is the addictive puzzle game where you slide numbered tiles on a grid to combine them and reach the magic number 2048. Simple to learn but challenging to master, this game will test your logic and strategy with every move.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys or swipe to slide tiles in any direction.</li>\n  <li>Combine matching numbers to create higher values.</li>\n  <li>Plan your moves carefully to avoid filling the board.</li>\n  <li>Keep going beyond 2048 to chase even higher scores!</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Easy-to-learn, challenging-to-master puzzle gameplay.</li>\n  <li>Endless replayability with different strategies.</li>\n  <li>Instant browser play with no downloads or sign-ups.</li>\n  <li>100% free and school-safe in this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play 2048 Unblocked?</h2>\n<p>2048 is the perfect game for puzzle lovers who enjoy strategy and problem-solving. With this <strong>unblocked version</strong>, you can play at school, work, or anywhere without restrictions. Challenge your brain, sharpen your logic, and see how high you can score!</p>\n\n<p><strong>👉 Play 2048 Unblocked now and test your puzzle-solving skills!</strong></p>\n"},
  { id: 7, "name":"Blackjack","file":"/games/blackjack.html","icon":"https://www.shutterstock.com/image-vector/blackjack-hand-spades-black-jack-600nw-2122961363.jpg","banner":"https://www.mobilityware.com/wp-content/uploads/2022/05/76608c_cf73479470cc44e18455ce9059982132_mv2.webp","desc":"<h1>🃏 Blackjack Unblocked – Play Online Free</h1>\n\n<p><strong>Blackjack Unblocked</strong> is the classic casino card game brought straight to your browser. Test your luck and strategy as you compete against the dealer to reach 21 without going over. Perfect for quick, fun gameplay sessions anytime, anywhere.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Each player is dealt two cards, and the dealer shows one face-up card.</li>\n  <li>Choose to \"Hit\" for another card or \"Stand\" to keep your total.</li>\n  <li>Try to get as close to 21 as possible without busting.</li>\n  <li>If your hand beats the dealer’s without going over, you win!</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Classic Blackjack rules with fast-paced gameplay.</li>\n  <li>Practice your strategy without risking real money.</li>\n  <li>Instant browser play – no downloads or accounts required.</li>\n  <li>100% free and school-safe in this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Blackjack Unblocked?</h2>\n<p>Blackjack is the ultimate mix of luck and skill, making it one of the most popular card games in the world. With this <strong>unblocked version</strong>, you can enjoy the thrill of the casino at school, work, or home – no restrictions, no stress. Sharpen your strategy and see if you can beat the dealer!</p>\n\n<p><strong>👉 Play Blackjack Unblocked now and put your card skills to the test!</strong></p>\n"},
  { id: 8, "name":"Snow Rider 3D","file":"/games/snowrider 3d.html","icon":"https://snowrider-3d.io/imgs/snowrider3d.png","banner":"https://bloximages.newyork1.vip.townnews.com/wfmz.com/content/tncms/assets/v3/editorial/2/0f/20fb5e48-c282-11ec-82b7-f7dd1aaba15d/62631c9fc3db1.preview.png?crop=512%2C269%2C0%2C57&resize=438%2C230&order=crop%2Cresize","desc":"<h1>🏂 Snow Rider 3D Unblocked – Play Online Free</h1>\n\n<p><strong>Snow Rider 3D Unblocked</strong> is a thrilling winter racing game where you ride a sleigh down snowy mountains at high speeds. Dodge obstacles, collect gifts, and see how far you can go in this endless downhill adventure.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys or WASD to steer your sleigh left and right.</li>\n  <li>Avoid trees, rocks, and other obstacles on the slopes.</li>\n  <li>Collect gifts along the way to increase your score.</li>\n  <li>Stay focused as the game speeds up the further you go!</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Exciting 3D graphics with a festive winter theme.</li>\n  <li>Endless gameplay for high-score challenges.</li>\n  <li>Simple controls that are easy to learn but hard to master.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Snow Rider 3D Unblocked?</h2>\n<p>Snow Rider 3D is perfect for players who love fast-paced endless runner games with a fun holiday twist. With this <strong>unblocked version</strong>, you can enjoy the game at school, work, or home without restrictions. Race down the slopes, dodge obstacles, and collect as many gifts as possible!</p>\n\n<p><strong>👉 Play Snow Rider 3D Unblocked now and experience the ultimate downhill sleigh ride!</strong></p>\n"},
  { id: 9, "name":"Run 3","file":"/games/run3.html","icon":"https://cdn2.steamgriddb.com/icon_thumb/833cc7b10966fa0202801496bffccb37.png","banner":"https://assets.funnygames.org/1/22861/76888/672x448/run-3.webp","desc":"<h1>🏃 Run 3 Unblocked – Play Online Free</h1>\n\n<p><strong>Run 3 Unblocked</strong> is the fast-paced endless runner where you guide a small alien through tunnels in outer space. Jump, dodge, and run across tricky platforms as the path keeps changing, testing your reflexes and timing.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys to move left and right through the tunnel.</li>\n  <li>Press the spacebar to jump over gaps and obstacles.</li>\n  <li>Switch between walls and floors to keep from falling into space.</li>\n  <li>Advance through endless levels and unlock new characters with unique abilities.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Unique outer space setting with rotating tunnels.</li>\n  <li>Multiple characters with different skills.</li>\n  <li>Endless gameplay with story and infinite modes.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Run 3 Unblocked?</h2>\n<p>Run 3 is perfect for fans of challenging endless runners that require quick thinking and precision. With this <strong>unblocked version</strong>, you can enjoy the game at school, work, or anywhere without restrictions. Explore space tunnels, test your reflexes, and see how far you can go!</p>\n\n<p><strong>👉 Play Run 3 Unblocked now and run through the galaxy’s most challenging tunnels!</strong></p>\n"},
  { id: 10, "name":"Basketball Stars","file":"/games/basketballstars.html","icon":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxKMfiklMLmio5eJsDFtmN0QYrbSjEfp3EQg&s","banner":"https://imgs.crazygames.com/games/basketball-stars-2019/cover-1583231506155.png?metadata=none&quality=100&width=1200&height=630&fit=crop","desc":"<h1>🏀 Basketball Stars Unblocked – Play Online Free</h1>\n\n<p><strong>Basketball Stars Unblocked</strong> is an exciting 2-player basketball game where you can dunk, shoot, and steal your way to victory. Play solo against AI or challenge a friend in fast-paced street basketball matches right in your browser.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys or WASD to move your player across the court.</li>\n  <li>Press the action keys to shoot, steal, or dash past your opponent.</li>\n  <li>Score baskets and block your rival to gain the lead.</li>\n  <li>Compete in 1v1 or 2-player mode for the ultimate basketball showdown.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Fast-paced basketball gameplay with fun animations.</li>\n  <li>Play against AI or a friend in local multiplayer mode.</li>\n  <li>Easy-to-learn controls that make every match exciting.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Basketball Stars Unblocked?</h2>\n<p>Basketball Stars is one of the most popular online basketball games, offering quick matches full of action and competition. With this <strong>unblocked version</strong>, you can shoot hoops and compete at school, work, or anywhere without restrictions. Show off your skills and dominate the court!</p>\n\n<p><strong>👉 Play Basketball Stars Unblocked now and prove you’re the ultimate baller!</strong></p>\n"},
  { id: 11, "name":"Five Nights At Freddy's (FNAF) 1","file":"/games/fivenights at freddy's (fnaf) 1.html","icon":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVIU3tE9qUPnGICYK5mM1ykVsUt43VVIndUQ&s","banner":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuKeQfGKE6Qn3R8NWSHAIMFZcGxtDDQ6LSmw&s","desc":"<h1>👾 Five Nights at Freddy’s 1 Unblocked – Play Online Free</h1>\n\n<p><strong>Five Nights at Freddy’s Unblocked</strong> (FNAF 1) is the original horror survival game that started it all. Step into the role of a night security guard at Freddy Fazbear’s Pizza, where animatronic characters come to life after dark. Survive five terrifying nights by monitoring cameras and conserving your limited power supply.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the security cameras to track Freddy, Bonnie, Chica, and Foxy.</li>\n  <li>Close the doors and turn on lights to keep animatronics away from your office.</li>\n  <li>Manage your limited power carefully throughout each night.</li>\n  <li>Survive all five nights without being caught to win.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Iconic survival horror gameplay that launched the FNAF series.</li>\n  <li>Chilling atmosphere with jump scares and suspense.</li>\n  <li>Simple point-and-click mechanics anyone can pick up.</li>\n  <li>100% free and school-safe with this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Five Nights at Freddy’s Unblocked?</h2>\n<p>FNAF 1 is a must-play for horror fans who love suspense, strategy, and jump scares. With this <strong>unblocked version</strong>, you can experience the terror at school, work, or home without restrictions. Keep your cool, outsmart the animatronics, and see if you can survive the week at Freddy’s Pizza.</p>\n\n<p><strong>👉 Play Five Nights at Freddy’s 1 Unblocked now and face the nightmare!</strong></p>\n"},
  { id: 12, "name":"Tetris","file":"/games/tetris.html","icon":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyD4tAXKhU2oPSZJNWjaUTjkjL7BioAh-I1A&s","banner":"https://images.ctfassets.net/u4t0f0gy4xt5/3kmer2KOGBKyLNuqnncZQA/7a7f2befc358116e633ee017277660d8/Tetris_banner.jpg?w=1200&h=630&q=50&fit=fill&f=top","desc":"<h1>🧩 Tetris Unblocked – Play Online Free</h1>\n\n<p><strong>Tetris Unblocked</strong> is the timeless puzzle game where you rotate and stack falling blocks to clear lines and keep the board from filling up. Simple to learn but endlessly addictive, this classic challenge has entertained players for decades.</p>\n\n<h2>🎮 How to Play</h2>\n<ul>\n  <li>Use the arrow keys to move and rotate falling blocks.</li>\n  <li>Complete horizontal lines to clear them from the board.</li>\n  <li>Plan ahead to keep your stack low and avoid reaching the top.</li>\n  <li>Survive as long as possible while aiming for a high score.</li>\n</ul>\n\n<h2>⭐ Features</h2>\n<ul>\n  <li>Classic puzzle gameplay loved worldwide.</li>\n  <li>Easy controls that anyone can pick up quickly.</li>\n  <li>Endless replay value with increasing difficulty.</li>\n  <li>100% free and school-safe in this unblocked version.</li>\n</ul>\n\n<h2>🚀 Why Play Tetris Unblocked?</h2>\n<p>Tetris is the ultimate puzzle experience, perfect for sharpening your mind, improving reaction time, and passing the time with fun, challenging gameplay. With this <strong>unblocked version</strong>, you can enjoy Tetris at school, work, or anywhere without restrictions. Test your skills and see how many lines you can clear!</p>\n\n<p><strong>👉 Play Tetris Unblocked now and enjoy the most iconic puzzle game ever created!</strong></p>\n"},

];

let search = document.createElement("input")
search.placeholder = "Search for a game..."
search.className = "searchinput"
search.oninput = (e) => {
  loadGames(e.target.value);
}
document.getElementById("games-sidebar").appendChild(search);
let searchResults = document.createElement("div");
document.getElementById("games-sidebar").appendChild(searchResults);

function loadGames(q) {
  searchResults.innerHTML = ``

  let query = q.trim().toLowerCase();

  for(let gamei in games) {
      let game = games[gamei];

      if(game.name.toLowerCase().includes(query)) {
        searchResults.innerHTML += `<a href='${window.location.origin}${game.file}'><img src='${game.icon}'>${game.name}</a>`
      }
    }
}


if(document.getElementById("new")) {
  for(let i = games.length-1; i > games.length - 10; i--) {
    if(games[i]) {
      document.getElementById("new").innerHTML += `<div onclick="window.location.href = '${window.location.origin}${games[i].file}'" class="game-card"><img src="${games[i].banner}"><h1>${games[i].name}</h1><div class="desc">${games[i].desc}</div></div>`;
    }
  }
}

if(document.getElementById("all")) {
  for(let i = 0; i < games.length; i++) {
    if(games[i]) {
      document.getElementById("all").innerHTML += `<div onclick="window.location.href = '${window.location.origin}${games[i].file}'" class="game-icon"><img src="${games[i].icon}"><h1 class="glass">${games[i].name}</h1></div>`;
    }
  }
}

loadGames("");

